apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: react-app
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/react-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values: {}
