apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: react-app
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/react-app
      sourceRef:
        kind: GitRepository
        name: react-gitops-demo
        namespace: flux-system
  values:
    image:
      repository: react-hello
      tag: latest
    service:
      type: NodePort
      port: 3000
